<div class="bs-docs-section">
	<div class="well">
	
<?php

$form->setAttribute('action', $this->url('admin/category', array('action' => 'create')));
$form->prepare();

echo $this->form()->openTag($form);
	echo '<fieldset><legend>Добавление категории</legend>';
	foreach ($form as $el)
	{
		echo '<div class="form-group">';
		$attributes = $el->getAttributes();
		
		if ($el->getLabel())
		{
			$el->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
			if (isset($attributes['required']))
			{
				$el->setLabel($el->getLabel() . ' *');
			}
		}
		
		if (isset($attributes['type']) && isset($attributes['type']) == 'text')
		{
			echo $this->formLabel($el);
			echo '<div class="col-lg-10">';
				echo $this->formInput($el);
			echo '</div>';
		}
		elseif (isset($attributes['type']) && isset($attributes['type']) == 'textarea')
		{
			echo $this->formLabel($el);
			echo '<div class="col-lg-10">';
				echo $this->formTextArea($el);
			echo '</div>';
		}
		elseif (isset($attributes['type']) && isset($attributes['type']) == 'file')
		{
			echo $this->formLabel($el);
			echo '<div class="col-lg-10">';
				echo $this->formFile($el);
			echo '</div>';
		}
		else
		{
			echo '<div class="col-lg-10">';
				echo $this->formRow($el);
			echo '</div>';
		}
		
		echo '</div>';
	}
	echo '</fieldset>';
echo $this->form()->closeTag();
?>

	</div>
</div>
	