<h1>Категории новостей</h1>

<a href="/admin/category/create/">Добавить</a><br><br>
<?php
	$flash = $this->flashMessenger();
	$flash->setMessageOpenFormat('<div%s>
	 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
		&times;
	 </button>
	 <ul><li>')
	 ->setMessageSeparatorString('</li><li>')
	 ->setMessageCloseString('</li></ul></div>');
	 
	echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>#</th>
			<th>Ключ</th>
			<th>Название</th>
			<th>Действие</th>
		</tr>
	</thead>
	<tbody>	
		<?php foreach ($categories as $category):?>
			<tr>
				<td><?=$category->getId()?></td>
				<td><?=$category->getCategoryKey()?></td>
				<td><?=$category->getCategoryName()?></td>
				<td>
					<a href="<?=$this->url('admin/category', array('action' => 'edit', 'id' => $category->getId()))?>">Редактировать</a>&nbsp;
					<a href="<?=$this->url('admin/category', array('action' => 'delete', 'id' => $category->getId()))?>" onclick="if (confirm('Удалить запись?')) { document.location = this.href; } return false;">Удалить</a>
				</td>
			</tr>
		<?php endforeach;?>
	</tbody>
</table>